### ISSUE TITLE
Error with remove-config in bulk export tool Exception in thread "main" java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by colinhuckstep** [pingidentity/pingidentity-devops-getting-started#375]
**Describe the bug**
When running the remove-config instruction in the pf-config.json for the ping-bulkexport-tools I recieve this error
Exception in thread "main" java.util.ConcurrentModificationException
	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1511)
	at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1534)
	at com.pingidentity.apac.pf.bulkconfigtools.App.processBulkJSONNode(App.java:150)
	at com.pingidentity.apac.pf.bulkconfigtools.App.processBulkJSONNode(App.java:173)
	at com.pingidentity.apac.pf.bulkconfigtools.App.processBulkJSONNode(App.java:173)
	at com.pingidentity.apac.pf.bulkconfigtools.App.processBulkJSON(App.java:130)
	at com.pingidentity.apac.pf.bulkconfigtools.App.<init>(App.java:88)
	at com.pingidentity.apac.pf.bulkconfigtools.App.main(App.java:45)

**To Reproduce**
1. Add the example remove-config block to the pf-config.json
"remove-config":[
    {
      "key": "id",
      "value": "ProvisionerDS"
    }
  ]
2. Run docker run --rm -v $PWD/shared:/shared ping-bulkexport-tools:latest /shared/pf-config.json /shared/data.json /shared/env_vars /shared/data.json.subst > ./shared/convert.log
3. See error

**Expected behavior**
I expect the tool to remove the ProvisionerDS Blocks from the data.json.subst

**Environment:**
 - Github Repo: [pingidentity-devops-getting-started](https://github.com/pingidentity/pingidentity-devops-getting-started)
 - Docker Container: ping-bulkexport-tools
 - Cloud Environment: Local Docker

**Comment by samir-gandhi** [comment]
I was able to reproduce the issue. I believe we need to leave empty arrays for unused functions. 
I was able to resole the issue by including empty arrays on pf-config.json. 
my final pf-config.json looked like:

```
{
  "add-config":[],
  "config-aliases":[
  ],
  "expose-parameters":[
  ]
  ,
  "remove-config":[
    {
    "key": "id",
    "value": "ProvisionerDS"
    }
  ]
}
```

Please try the same and let us know. 

If this approach works I think just tracking this in docs would be enough of a fix.
